### ISSUE TITLE
Using it with Vuex

### ISSUE THREAD

**Issue by ghost** [dmlzj/vlf#1]
Hi, its possible to use this inside of my store with vuex? the code on the readme only shows how to implement in individual componets but how is the procedure for integrating with vuex?

**Comment by dmlzj** [comment]
```js
import Vue from 'vue'
import Vuex from 'vuex'
import Vlf from 'vlf'
Vue.use(Vlf)
Vue.use(Vuex)
```

**Comment by RomanLavrinenko** [comment]
Hi, i think it's still not clear how to get an instance of Vlf not in code of component like it described in readme `this.$vlf`.
For example i need it in my auth class but `Vue.vlf` and `this.$vlf` doesn't work for me.
Thanks.

**Comment by AAhrit** [comment]
What I did inside of vuex was created a plugin that use the localforage api directly. I think that depends on the type of app you are doing

**Comment by RomanLavrinenko** [comment]
@AAhrit thanks for the answer.
What i try is to create an util named async-local-storage.js 
create and export an instance of `vlf` like this:
```
import Vue from 'vue';
import Vlf from 'vlf';

Vue.use(Vlf);

const als = Vue.vlf;
export default als.creageInstance({
  storeName: 'test',
});
```
to have ability use in my classes, but still have no luck.

**Comment by dmlzj** [comment]
In yourself class，you don't need  'Vue use Vlf',you just 'import Vlf from vlf'.
